name: Deploy to Firebase Cloud Functions

on:
  push:
    branches:
      - main
      - dev
    paths:
      - firebase/**
      - .github/workflows/deploy-functions.yml
  workflow_dispatch:

env:
  service_account_prod: github-actions@genshin-material.iam.gserviceaccount.com
  service_account_dev: github-actions@genshin-material-dev.iam.gserviceaccount.com

jobs:
  deploy:
    name: Deploy to Firebase Cloud Functions
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: "**/yarn.lock"

      - name: yarn install
        working-directory: firebase/functions
        run: yarn install --frozen-lockfile

      - name: Install Firebase CLI
        run: yarn global add firebase-tools

      - name: 'Authenticate to Google Cloud'
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: projects/1018400803757/locations/global/workloadIdentityPools/github-actions/providers/github
          service_account: ${{ github.ref_name == 'main' && env.service_account_prod || env.service_account_dev }}
          audience: https://github.com/chika3742

      - name: Deploy to Cloud Functions (dev)
        if: github.ref_name == 'dev'
        run: yarn firebase-deploy:dev --debug

      - name: Deploy to Cloud Functions (prod)
        if: github.ref_name == 'main'
        run: yarn firebase-deploy:production